<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Desk Configuration</name>
   <tag></tag>
   <elementGuidId>a0e4b911-94f6-41ae-8978-0c7022aa9385</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.top-nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainRouterContainer']/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Desk Configuration&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>424609a0-2b7f-4092-b4e7-852010577fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>67a59ef4-a25d-4759-9ca0-ed6842e2074b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-nav-link</value>
      <webElementGuid>4ce15eaa-d8d2-40dd-8f53-b87378953c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desk Configuration</value>
      <webElementGuid>38571e84-8706-476a-a3cd-f1ad1fdd4aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainRouterContainer&quot;)/div[@class=&quot;dashboard-container-wrapper&quot;]/div[@class=&quot;top-nav&quot;]/div[@class=&quot;top-nav-section&quot;]/a[@class=&quot;top-nav-link&quot;]</value>
      <webElementGuid>23242364-7a2b-4e5e-b832-72b1b195ef77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainRouterContainer']/div/div/div/a</value>
      <webElementGuid>db222caa-c79d-46b6-b759-ba7238995e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Desk Configuration')]</value>
      <webElementGuid>a6ef81a3-bb09-4ede-8de2-3c0a477823ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List is empty.'])[1]/following::a[1]</value>
      <webElementGuid>31b30b1d-ff87-46a3-a2f1-8212611f2666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No elements found. Consider changing the search query.'])[1]/following::a[1]</value>
      <webElementGuid>d7e8028e-c70a-4f53-8457-deca80ad90e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quote'])[1]/preceding::a[1]</value>
      <webElementGuid>d40f7447-b2be-4f37-ad42-304c8f1995f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Recent Desks'])[1]/preceding::a[2]</value>
      <webElementGuid>6e3d5bca-5c9b-48c2-8c4f-50f24b7ed412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Desk Configuration']/parent::*</value>
      <webElementGuid>d67714e6-4b71-4f3b-ae68-0a3098399ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>50cd7c8d-99c0-478b-992d-3b014991dcf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>c76e3d8a-e7df-4d68-8033-857ac7bac5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Desk Configuration' or . = 'Desk Configuration')]</value>
      <webElementGuid>a12f2886-907a-428e-9653-8a555d78a220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
