<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Custom Calculations_multiselect__select</name>
   <tag></tag>
   <elementGuidId>4d018431-c3df-4b11-b55a-4c81d3865c9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainRouterContainer']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.multiselect__select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox >> div >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1edad2d4-c545-44e8-a01e-a22331ee363d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect__select</value>
      <webElementGuid>85f621f8-a5f7-4d78-baac-fda3fe3d4592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainRouterContainer&quot;)/div[@class=&quot;dashboard-container-wrapper&quot;]/div[@class=&quot;top-nav&quot;]/div[@class=&quot;top-nav-section&quot;]/div[@class=&quot;multiselect store-dropdown ml-3 multiselect--active&quot;]/div[@class=&quot;multiselect__select&quot;]</value>
      <webElementGuid>4ae625f8-b227-4ddf-bfd0-868ef49dc37b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainRouterContainer']/div/div/div/div/div</value>
      <webElementGuid>24b476ae-31ec-4782-9696-15a3e86c48d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>30df5046-44f8-4076-91d2-652c422cca1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
