<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Demo Dealerships_store-switcher-icon</name>
   <tag></tag>
   <elementGuidId>60ed0a74-8ec8-40ae-a09c-8755d0678618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.store-switcher-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global_frame_store_switcher']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Demo Dealerships (Click here to change stores)&quot;i] >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>853dfa38-508b-4e73-8ba2-ffc2fa05737c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://stage-assets.autoalert.com/img/global-frame/icon-stores-vanilla.svg</value>
      <webElementGuid>020121c4-c098-4ccc-9dca-85ded83e5642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>store-switcher-icon</value>
      <webElementGuid>d67ae123-7058-4c4e-8ffb-3ebc3d3576a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global_frame_store_switcher&quot;)/div[@class=&quot;info-text&quot;]/img[@class=&quot;store-switcher-icon&quot;]</value>
      <webElementGuid>a4de2713-7c2c-4d4e-bdb5-220de62b228b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global_frame_store_switcher']/div/img</value>
      <webElementGuid>deb1e54d-59b2-42e0-b5cd-5f25a8e05b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://stage-assets.autoalert.com/img/global-frame/icon-stores-vanilla.svg')]</value>
      <webElementGuid>55717e04-dcb2-4acd-8a30-3025d9996f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/img</value>
      <webElementGuid>d4a705e7-9a05-4357-9581-8cb9cec669a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://stage-assets.autoalert.com/img/global-frame/icon-stores-vanilla.svg']</value>
      <webElementGuid>e617bb50-90c8-4a2f-b05a-a8ea546ba3c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
