<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Demo Dealerships_store-switcher-icon</name>
   <tag></tag>
   <elementGuidId>60ed0a74-8ec8-40ae-a09c-8755d0678618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global_frame_store_switcher']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.store-switcher-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Demo Dealerships (Click here to change stores)&quot;i] >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6056c293-220b-4637-9175-9074b66c2ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://stage-assets.autoalert.com/img/global-frame/icon-stores-vanilla.svg</value>
      <webElementGuid>4d3aa5aa-21bd-47c8-bef9-7f808d718914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>store-switcher-icon</value>
      <webElementGuid>0b9049e2-258d-4fb7-bc1c-53f4b7bddc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global_frame_store_switcher&quot;)/div[@class=&quot;info-text&quot;]/img[@class=&quot;store-switcher-icon&quot;]</value>
      <webElementGuid>d2cfbdf0-9682-4440-bec8-dc5328341687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global_frame_store_switcher']/div/img</value>
      <webElementGuid>0ee935d2-b63d-4998-a4de-8cb581a4a5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://stage-assets.autoalert.com/img/global-frame/icon-stores-vanilla.svg')]</value>
      <webElementGuid>c4a3371f-a089-4d07-b800-f109ad0656a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/img</value>
      <webElementGuid>9685633f-0229-4f2f-925b-3667ab1e44c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://stage-assets.autoalert.com/img/global-frame/icon-stores-vanilla.svg']</value>
      <webElementGuid>712542af-ac65-4e62-8d83-64804750574a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
