<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_M. I_add_prospect_middle_nameTxt</name>
   <tag></tag>
   <elementGuidId>d16e57c5-435f-4a03-b7a0-53fd619f7fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add_prospect_middle_nameTxt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add_prospect_middle_nameTxt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Middle Initial&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ec2d816-7cbf-465d-ad03-805c98e2e183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7effd403-8a91-4471-8f9d-19c13d5a5a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Middle Initial</value>
      <webElementGuid>7319e42e-0854-4b9e-90fd-1aaf591c316d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add_prospect_middle_nameTxt</value>
      <webElementGuid>f4982060-6c2e-48db-a226-d7a121dcbef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d6a6eb0a-8a37-43cd-8f98-8d2bd7fdb3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add_prospect_middle_nameTxt&quot;)</value>
      <webElementGuid>c05d3ad7-a7d0-4e17-aa33-ca8909ecd1c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add_prospect_middle_nameTxt']</value>
      <webElementGuid>3505ad7c-8fdd-44e8-b3cc-57d7864147ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profile_info_section']/div[6]/div[2]/input</value>
      <webElementGuid>3e432b5d-8317-4e59-930a-765651b94a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>9ad2d830-9968-4305-b6d5-756af5c7343b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Middle Initial' and @id = 'add_prospect_middle_nameTxt']</value>
      <webElementGuid>ef983636-7bbc-4ec5-9f59-2a5aa706f742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
