<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_847473</name>
   <tag></tag>
   <elementGuidId>d396c486-17db-40b9-bab8-93824fb9faae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.ant-typography.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Last MFA code for: +15598211254'])[1]/following::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;847473&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7bd55aa0-7281-414f-b266-2e412b6b46c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-typography ng-star-inserted</value>
      <webElementGuid>e755459d-7df2-4889-b444-8b7a41d66bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>847473  </value>
      <webElementGuid>f5c40f0a-7b89-44ea-8e22-eda5ee03fa32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout&quot;]/nz-content[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/nz-spin[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/app-last-mfa-code[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login&quot;]/nz-card[@class=&quot;ant-card ant-card-bordered&quot;]/div[@class=&quot;ant-card-body&quot;]/nz-skeleton[@class=&quot;ant-skeleton ant-skeleton-active ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/h1[@class=&quot;ant-typography ng-star-inserted&quot;]</value>
      <webElementGuid>e7ff5fe3-c01d-4599-abd6-f703a965d97d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last MFA code for: +15598211254'])[1]/following::h1[1]</value>
      <webElementGuid>457d4e76-7f45-4718-9b0a-e5cd31c56f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MFA'])[1]/following::h1[1]</value>
      <webElementGuid>40ce233e-a990-442e-8e9d-93120988d06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::h1[1]</value>
      <webElementGuid>21bf2145-2e34-4d82-bcda-f619c68a208f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/preceding::h1[1]</value>
      <webElementGuid>0b15d1f8-3c75-444d-852c-03494707537b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='847473']/parent::*</value>
      <webElementGuid>0e64432d-9cae-48ae-a256-b7996ca99311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-skeleton/div/h1</value>
      <webElementGuid>ce01016e-f93f-4ae2-a395-23c3e135b5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '847473  ' or . = '847473  ')]</value>
      <webElementGuid>0485969d-bc6e-4199-94e3-a48957a8acfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
