<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Or_ant-input ng-untouched ng-star-ins_a66743</name>
   <tag></tag>
   <elementGuidId>236b820c-9aef-486b-bab5-9d091fd4339b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.ng-untouched.ng-star-inserted.ant-input-status-success.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93b3da01-262b-4909-8009-a9cc859ad9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2c15377a-2c4a-4c41-8110-725cbf31145b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5481bfe3-ea91-4030-97a4-f7e2b39a5c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>6bc1fc6a-61c8-471f-9e63-05262c29904d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ng-untouched ng-star-inserted ant-input-status-success ng-dirty ng-valid</value>
      <webElementGuid>9644ee4e-4008-49ca-a207-f73de592ad03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/nz-layout[@class=&quot;ant-layout&quot;]/nz-content[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/nz-spin[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;login&quot;]/nz-card[@class=&quot;ant-card ant-card-bordered&quot;]/div[@class=&quot;ant-card-body&quot;]/nz-skeleton[@class=&quot;ant-skeleton ant-skeleton-active ng-star-inserted&quot;]/form[@class=&quot;login-form ant-form ant-form-horizontal ng-star-inserted ng-dirty ng-touched ng-valid&quot;]/nz-form-item[@class=&quot;ant-row ant-form-item ant-form-item-has-success&quot;]/nz-form-control[@class=&quot;ng-tns-c136-1 ant-form-item-control ant-col ng-star-inserted&quot;]/div[@class=&quot;ant-form-item-control-input ng-tns-c136-1&quot;]/div[@class=&quot;ant-form-item-control-input-content ng-tns-c136-1&quot;]/nz-input-group[@class=&quot;ng-tns-c136-1 ant-input-affix-wrapper cdk-focused cdk-mouse-focused ant-input-affix-wrapper-focused ant-input-affix-wrapper-status-success&quot;]/input[@class=&quot;ant-input ng-untouched ng-star-inserted ant-input-status-success ng-dirty ng-valid&quot;]</value>
      <webElementGuid>17649411-750d-4c9a-9295-e85c9aeef7d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>032ff61a-cc5a-4981-b1ba-4e9ac1898094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nz-form-item[2]/nz-form-control/div/div/nz-input-group/input</value>
      <webElementGuid>aee71540-9abd-4b2e-a4b8-cd02e3c1edc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>e0f9e84b-252f-4de2-a623-d2f9715b3f27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
