<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CXM_app-link-icon-wrapper</name>
   <tag></tag>
   <elementGuidId>84dde537-f382-4a9e-98f4-e88082898a2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#app_switcher_list_item_11 > a.app-link > div.app-link-icon-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app_switcher_list_item_11']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Desking&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b128d96f-c6b1-43da-87e0-2b9d914f2378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-link-icon-wrapper</value>
      <webElementGuid>cda44f11-aa63-47af-a5db-3e854c3dba24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_switcher_list_item_11&quot;)/a[@class=&quot;app-link&quot;]/div[@class=&quot;app-link-icon-wrapper&quot;]</value>
      <webElementGuid>1d08a8e5-f125-4b4d-833b-427978b42b6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app_switcher_list_item_11']/a/div</value>
      <webElementGuid>2dbce0ff-184c-403b-8c32-38a5eab15824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CXM'])[1]/following::div[2]</value>
      <webElementGuid>69bbf113-90ac-41e7-80c7-449d1e887f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inbox'])[1]/following::div[5]</value>
      <webElementGuid>dc2075c8-ba42-49d7-9a7d-08ef76cbda90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desking'])[1]/preceding::div[1]</value>
      <webElementGuid>e49bf970-147b-43c1-b401-9d9a712b58d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store'])[1]/preceding::div[3]</value>
      <webElementGuid>43b3a2e0-3bed-4414-a360-1cb6f0654c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div</value>
      <webElementGuid>2d4f6f83-ad6a-4447-9550-3b9da1363337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
